### PR TITLE
Move period to it's correct position.

### PR DESCRIPTION
**Pull request by anonx**
We should use either spaces or tabs. Not both. + #71 that was merged to `master`.

### CODE REVIEW

**Comment by brendensoares** [comment]
I'm all about tabs :+1:

**Comment by notzippy** [comment]
We should follow gofmt standards `Gofmt formats Go programs. It uses tabs (width = 8) for indentation and blanks for alignment.`

**Comment by anonx** [comment]
@notzippy Yeah, but this is not go code. It's html. And we have already had spaces. I just removed a few tabs.
Though I personally prefer tabs and I would agree to use tabs instead of spaces for our html.

**Comment by notzippy** [comment]
@anonx ok, didn't notice it was html, personally I am all about the spaces outside of go code (python work) tabs were always a nightmare waiting to happen...

**Comment by brendensoares** [comment]
@anonx just to chime in, i don't understand why HTML should use spaces. Since it's transferred over the wire, it has even more reason to not use spaces for indentation.

Tabs are user adjustable and therefore are more flexible that spaces. They're also less cheracters to store. It's reasons like this that I prefer tabs over spaces.

**Comment by anonx** [comment]
> i don't understand why HTML should use spaces

@brendensoares, I don't understand, too. But 2 spaces is a [standard in google](https://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml?showone=Indentation#Indentation). That's probably because Rob [used](https://github.com/robfig/revel/blob/gh-pages/index.html) [it](https://github.com/robfig/revel/blob/master/skeleton/app/views/header.html) for Revel.

As for transferring over wire, the number of spaces is not important. The response is likely to be compressed anyway.

P.S.: Tabs, spaces... Doesn't really matters much. Just let's be consistent. But if somebody wants they can replace all spaces by tabs. I would support that decision.

**Comment by brendensoares** [comment]
@anonx I'll probably replace all spaces with tabs at some point in the future.

**Pull request merged**
