### PR TITLE
Correct the link to the controllers page

### PR DESCRIPTION
**Pull request by nigelramsay**
There was a missing 's'

### CODE REVIEW

**Comment by pedromorgan** [comment]
thanks

**Comment by brendensoares** [comment]
@pedromorgan did you merge this into `master` too?

**Comment by pedromorgan** [comment]
I think so..
Dont worry.. am tidying up a few missing things in docs..

and also gonna make master the default "correct branch" cos we getting all patches against "mistakes">.

so front end it is driving.. and move that into upstream develop

and still trying to figure out a stratergy..
eg a script that automatically merges changes to master  and not in develop

**Comment by pedromorgan** [comment]
and the version.yaml is messing me up cos I dont expect a "backwards pass" (welsh rugby term, a game played my men with oval shaped balls)

**Comment by brendensoares** [comment]
@pedromorgan I feel like `develop` needs to stay the default branch to follow our git workflow. At the very laest, make sure patch fixes get into both `develop` and `master.

**Pull request merged**
