### PR TITLE
fixed spelling error indicated in latest issue

### PR DESCRIPTION
**Pull request by DGKSK8LIFE**

### CODE REVIEW

**Comment by DGKSK8LIFE** [comment]
idk how build failed the only thing I changed was one html file

**Comment by DGKSK8LIFE** [comment]
[latest issue](https://github.com/revel/revel.github.io/issues/193)

**Comment by notzippy** [comment]
Thanks!

**Comment by DGKSK8LIFE** [comment]
> Thanks!

FINALLY! Thanks for the merge man!

**Pull request merged**
