### PR TITLE
Revamp homepage

### PR DESCRIPTION
**Pull request by manfordbenjamin**
Hi guys, so once again i decided to revamp the homepage. Please let me know what you think.

landing_page_1
landing_page_2
landing_page_3

### CODE REVIEW

**Comment by manfordbenjamin** [comment]
Sure, i can apply the styling throughout the site

**Comment by pedromorgan** [comment]
nice... Re style.. is it time to switch to scss ??

**Comment by pedromorgan** [comment]
Note: With gitlab pages a job/script is run created to "site" including eg scss > css.. Not sure this possible with jekyll

**Comment by manfordbenjamin** [comment]
Not sure. Do you guys have any design guidelines??

**Comment by pedromorgan** [comment]
@manfordbenjamin not that i'm aware off..

**Comment by manfordbenjamin** [comment]
So i extended the new theme to the rest of the pages and this is how it looks. I also changed the logo and cleaned up the code snippet design.

landing_page_1
manual
concepts

**Comment by notzippy** [comment]
Looks really nice @manfordbenjamin Ill test it out once I am home again but it looks like a nice refresh to me - what are your thoughts @pedromorgan ?

**Comment by manfordbenjamin** [comment]
@notzippy Glad you like it

**Pull request merged**
