### PR TITLE
Update interceptors.md

### PR DESCRIPTION
**Pull request by eric-gilbertson**
The text describes using InterceptFunc to intercept requests to any/all controllers but as shown it does this only for hotel requests. This change aligns the example with the description for 'Func.

### CODE REVIEW

**Comment by brendensoares** [comment]
@pedromorgan why did you merge this into `master`? Shouldn't have been merged into `develop`??

**Comment by pedromorgan** [comment]
OOps my mistake, assumed it was targetted at "develop".. will try and fix when I get home..

**Comment by pedromorgan** [comment]
Absolutely confused how to undo this ??

revert gives me another pull request.. on gh.. and never done this kinda thing in git !!

**Comment by anonx** [comment]
@pedromorgan First of all, show the list of latest commits:
```sh
$ git log
```

> commit 17240b5beaed02e266d384635bdaede37a53730d
> Merge: 422645f 8f293af
> Author: Pete Morgan <pedromorgan@gmail.com>
> ...
>
>
> commit 8f293afac2166690969ab677982ef0546bdaec6c (THIS IS THE PREVIOUS ONE)

We are interested in the previous one `8f293afac2166690969ab677982ef0546bdaec6c`, so:
```sh
git checkout 8f293afac2166690969ab677982ef0546bdaec6c
```
And then:
```sh
git reset --hard
```

So, the history is virgin again and all we have to do is to rewrite the history (perhaps, you **do not** have rights to do it; I don't know):
```sh
git push origin master --force
```

**Comment by pedromorgan** [comment]
am too nervous to do that.. 
not in master..

**Comment by pedromorgan** [comment]
apologies for a spurious merge.. but i thought it was at develop branch

**Comment by pushrax** [comment]
This is fine isn't it? The change applies to all versions of Revel.

**Comment by anonx** [comment]
@pushrax, you are right. And we didn't intend to revert anything, we just have some nice dialogue here.
@brendensoares asked why this is in `master` rather than `develop`. @pedromorgan asked how could that in theory be reverted. And I answered how. Whereupon @pedromorgan concluded that it is very exciting to merge things.

**Comment by brendensoares** [comment]
Well, other than going against our defined workflow, this merge into `master` should be okay (I hope). Git should be able to merge `develop` into `master` later without losing this patch.

In the future, don't do this :)

**Comment by pedromorgan** [comment]
Apologies..

**Pull request merged**
